"use client";
import { Container } from "@chakra-ui/react";

import { Header } from "@/components/Header";

import { Footer } from "@/components/Footer";
import "./globals.css";
import { Inter, Roboto } from "next/font/google";
import { Providers } from "./providers";
import { BackButton } from "@/components/Button";
import { usePathname } from "next/navigation";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          <Header />
          {pathname !== "/courses" && <BackButton />}
          <Container>{children}</Container>
        </Providers>
      </body>
    </html>
  );
}
